services:
  web:
    build: ../dziupla-app
    ports:
      - "80:80"
  backend:
    build: ../dziupla-back
    ports:
      - "8001:8001"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dziupla
      MYSQL_USER: dziupla
      MYSQL_PASSWORD: dziupla
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
