services:
  web:
    container_name: dziupla-web
    build: 
      context: ../dziupla-app
      args:
        build_env: development
    ports:
      - "80:80"
  backend:
    container_name: dziupla-backend
    build: ../dziupla-back
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: dziupla-db
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dziupla
      MYSQL_USER: dziupla
      MYSQL_PASSWORD: dziupla
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
